### ISSUE TITLE
Nil pointer deref on opening a file within a zip file

### ISSUE THREAD

**Issue by milkpirate** [mholt/archives#3]
## What version of the package or command are you using?
`v0.0.0-20241119192853-c1ebc8406725`

## What are you trying to do?
Use an existing ZIP file as a file system.

## What steps did you take?
```golang
package main

import (
	"context"
	"github.com/mholt/archives"
	"github.com/sanity-io/litter"
	"os"
)

func main() {
	compressed, err := os.Open("C:\\artifacts.zip")
	if err != nil {
		panic(err)
	}
	defer compressed.Close()

	compressedContent := new(bytes.Buffer)
	_, err = io.Copy(compressedContent, compressed)
	if err != nil {
		panic(err)
	}

	afs, err := archives.FileSystem(context.Background(), "", bytes.NewReader(compressedContent.Bytes()))
	if err != nil {
		panic(err)
	}

	file, err := afs.Open("response")
	if err != nil {
		panic(err)
	}
	defer file.Close()
        ...
}
```

## What did you expect to happen, and what actually happened instead?
The program from above panics with a nil pointer dereference:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x64a8c8]

goroutine 1 [running]:
github.com/mholt/archives.(*Archive).OpenReader(0x993710?, {0x781f20?, 0xc000022ea0?})
	<autogenerated>:1 +0x28
github.com/mholt/archives.ArchiveFS.Open({{0x0, 0x0}, 0xc000022e70, {0x781f80, 0xc000022e40}, {0x0, 0x0}, {0x784b10, 0x9eb960}, 0x0, ...}, ...)
	C:/Users/<user>/go/pkg/mod/github.com/mholt/archives@v0.0.0-20241119192853-c1ebc8406725/fs.go:354 +0xbff
main.main()
	C:/Users/<user>/AppData/Roaming/JetBrains/GoLand2024.2/scratches/main.go:22 +0xca
```

## How do you think this should be fixed?
From the debugger it seems to panic exactly here: https://github.com/mholt/archives/blob/main/fs.go#L354 I used the stream option, since in my use case the file will be in memory and I really would want to avoid writing it to a temp-fs or so.

## Please link to any related issues, pull requests, and/or discussion
🤷🏻 

## Bonus: What do you use this package for, and do you have any other suggestions or feedback?
Here you return "just" the `fs.FS` interface: https://github.com/mholt/archives/blob/main/fs.go#L45 even though the object returned implements much more then just `fs.FS` (and its `.Open()`) e.g. `fs.ReadDirFile` (like in https://github.com/mholt/archives/blob/main/README.md?plain=1#L193).

Downcasting is always possible, but upcasting requires code and `err` handling (that need to be tested) which can be avoided if you use the broadest interface that the struct implements.

If there is no interface that covers all create a new one including all interfaces which are implemented and return that since then its implementing all the "child" interfaces.

**Comment by mholt** [comment]
I actually was working on this while you were posting this, I only just saw it now but can you pull the latest from main and see if it still happens for you?

**Comment by milkpirate** [comment]
😄 Yes! Works!

**Comment by mholt** [comment]
Excellent!

**Comment by milkpirate** [comment]
Can I convince you about the interface? Since all the structs `archives.FileSystem(...)` returns, seem to implement at least:
```golang
fs.FS
fs.ReadDirFS
fs.StatFS
```

**Comment by mholt** [comment]
Possibly. But my understanding is it's best practice to just return `fs.FS` and then let type assertions do the rest. So for example, the `fs` package functions, such as `fs.Stat`, will type-assert to `StatFS` and use it.

I don't _suppose_ there will be new FS types added later, but it may be hard to do so if we make the interface more complex.

One other reason to use `fs.FS` is because most other code out there uses vanilla `fs.FS`. Your code will need to have separate code paths, because if the FS you're using doesn't implement 1 of the 3 interfaces, for example, now you need to handle that case. I think in general it's best to be minimal with what you declare and let users type-assert as necessary.

I could probably still be convinced, but let's discuss it more. Is the main motivation to avoid type assertions? (In most cases, your own code will not need to do them, the `fs` package does them for you.)

**Comment by milkpirate** [comment]
I know what you mean, but I would say to **use** a minimal interface but supply the most broad.

The main motivation is not just avoiding assertions, its more convenience. 

My use case is as follows. I read (download) a file (the zip file... or preferably any kind of archive, that why I like you package) into mem. Then I want to list the files in it and process them further one after the other by opening/reading them.

So first I thought, what is a FS useful for, if you dont know whats in it? One would have to know in advance how how the archive is structured. So I think at least listing should be possible. Honestly just need the `Open()` and `ReadDir()` methods. But I am pretty sure thats just my opinion because of the use case, other might think the same about stat-ing and maybe just need `Stat()`.

I just see this collapsing to a one-liner:
```golang
func (uu *Universal) Unpack(compressedBytes *bytes.Reader) (fs.ReadDirFS, error) {
	ctx := context.TODO()

	afs, err := archives.FileSystem(ctx, "", compressedBytes)
	if err != nil {
		return nil, errors.Wrap(err, errCompressedFS)
	}

	rdfs, ok := afs.(fs.ReadDirFS)
	if !ok {
		return nil, errors.New(errCastToReadDirFile)
	}

	return rdfs, nil
}
```
-> 
```golang
func (uu *Universal) Unpack(compressedBytes *bytes.Reader) (fs.ReadDirFS, error) {
	return archives.FileSystem(context.TODO(), "", compressedBytes)
}
```

**Comment by mholt** [comment]
Since all the file systems do implement ReadDirFS:

```
func (uu *Universal) Unpack(compressedBytes *bytes.Reader) (fs.ReadDirFS, error) {
	fsys, err := archives.FileSystem(context.TODO(), "", compressedBytes)
	return fsys.(fs.ReadDirFS), err
}
```

Is that acceptable? :grin:

**Comment by milkpirate** [comment]
🤔 when its exploding at compile time, yes.

**Comment by mholt** [comment]
Not sure what you mean, sorry? Does it not compile?

**Comment by milkpirate** [comment]
I mean if you ever change you source and return a struct that e.g. does not implement `fs.ReadDirFS`, will I notice it at compile time, will the compiler complain instead of panic-ing on runtime?

**Comment by mholt** [comment]
If I codify it into the signature, I'm not able to return any such type without breaking _everyone_ (since I'd have to revert the signature back to a more basic `fs.FS`). That means either I break everyone or I release a new major version, which means any users of the previous version won't receive updates (because let's be honest, I won't have the energy to maintain two major versions). And then _everyone_ needs to update their code bases to upgrade, refactor their code, etc.

Hence, maybe it is better to return `fs.FS` so that individual consumers can type-assert.

**Comment by milkpirate** [comment]
Yes, I got that, this is not what I meant.

I am talking about this line `return fsys.(fs.ReadDirFS), err` if you ever change the `struct`(s) returned from `archives.FileSystem()` to not implement `fs.ReadDirFS` any more, when will my code fail if I bump the version? Will it fail at linting, compiling or runtime (the worst of them all)?

**Comment by mholt** [comment]
@milkpirate Oh, I see what you mean. It will fail at runtime. :innocent:

If we do it the other way, it fails at compile-time, for everyone. Either that or I do a proper version bump and they just stop getting updates to the library (including potential security updates).

**Comment by milkpirate** [comment]
Then your proposed version might panic without proper error handling if the underlying struct is changes. So we're back to my original version.

I guess you refering to"be lose with inputs and strict with output" though this applies to adhering to standards (and so interfaces), however they might look like. Adhering strictly to a broader interface does not violate this.

I think it is just inconvenient and that I have superfluous code to be save if thats avoidable in the first place. `fs.ReadDirFS -> fs.FS -(error checking)-> fs.ReadDirFS` while one could just to use the `fs.ReadDirFS` in the first place.

The user has no downside in receiving a broader interface and its even more flexible for him.

But I get the point you want to keep it minimal for (possibly) future development.

It depends on what you value more, UX (I do as I am a user) or DX (you do as teh developer/maintainer)

As I said. Its your show 😄, you decide and if I havent convinced you till now I dont have more arguments to do so 🤷🏻 So no big deal, I do the type assertion and you will be flexible for future development.

**Comment by mholt** [comment]
> Then your proposed version might panic without proper error handling if the underlying struct is changes. So we're back to my original version.

Yeah... that's kind of the point though. Either your project breaks, or I break everyone's. The most robust and flexible thing to do is for us to return the basic fs.FS interface, and let users type-assert to what they need. No breakage!

---

Anyway, not to shut down the idea. I'll still think on it. Maybe we'll see if there are any further requests for it. Just currently not feeling quite compelled enough to codify it into the signature

**Comment by milkpirate** [comment]
Just heard a talk, some part addressed our very discussion 😄 
![image](https://github.com/user-attachments/assets/87a79123-845e-442a-a0ee-22ad3edca6f1)

**Comment by mholt** [comment]
The Go convention -- not just this package -- is to return `fs.FS` because returning `fs.ReadDirFS` is more misleading if it's also a `fs.StatFS`, and/or `fs.ReadFileFS` and/or `fs.SubFS`, etc etc. The types are disjoint and you can only return one, so the common denominator is `fs.FS`.

**Comment by mholt** [comment]
It would quite litter an exported API to have an exponentially-growing set of interfaces that are all the combinations of each other.

What's wrong with the conventional type assertion? Just assert what you need. Define your own type if you really need to.

**Comment by Merovius** [comment]
Found this via Mastodon. I'm surprised no one has mentioned that the actually recommended way to do this is to use [fs.ReadDir](https://pkg.go.dev/io/fs#ReadDir), not to type-assert on `fs.ReadDirFS`. The same for any other optional interfaces in `io/fs`.
