### ISSUE TITLE
Extract inner archive from archive

### ISSUE THREAD

**Issue by nicola-spb** [mholt/archives#4]
Hello

## What are you trying to do?
I have zip archive with inner zip archive. Structure like this:

archive.zip contains:
  - archive2.zip
  - archive3.zip

When I try extract inner archives I got error: 

> input type must be an io.ReaderAt and io.Seeker because of zip format constraints

```
format, _, err := archives.Identify(ctx, filepath.Base(archiveFileName), r)
if err != nil {
	return nil, fmt.Errorf("failed identify type of archive \"%s\"; %w", archiveFileName, err)
}

ex, ok := format.(archives.Extractor)
if !ok {
	return nil, fmt.Errorf("failed extract files from archive \"%s\" because format \"%s\" has not extractor", archiveFileName, format.Extension())
}

err = ex.Extract(ctx, r, func(ctx context.Context, f archives.FileInfo) error {
	if err != nil {
		return err
	}

	if f.IsDir() {
		return nil
	}

	// do something...

}
```

How can I extract inner archive2.zip and archive3.zip from archive.zip?

**Comment by mholt** [comment]
I don't think it is possible, since the zip package gives us a reader, not a seeker.

Maybe there's a clever way but I don't know it.

**Comment by nicola-spb** [comment]
ok. I thought it my mistake or I don't know method of do it.
My archive is smal and a fix it for myself. I extract archive to temp folder and read from there.

Thank you.

**Comment by mholt** [comment]
No worries. I'd love to solve that but just don't know enough or have time for it 😓
