### ISSUE TITLE
problem when calling WalkDir in some cases

### ISSUE THREAD

**Issue by Koyorice** [mholt/archives#5]
## What version of the package or command are you using?

v0.0.0-20241207175349-5e373c52f8aa

## What are you trying to do?

Call `WalkDir` on a compressed archive containing Chinese file name
If you don’t have the zip file you can download this [test.zip](https://github.com/user-attachments/files/18136647/test.zip)

## What steps did you take?
Create a compressed file and put files or folders named in Chinese into it

```
ctx := context.Background()
fsys, err := archives.FileSystem(ctx, "test.zip", nil)
if err != nil {
	panic(err)
}
err = fs.WalkDir(fsys, ".", func(path string, d fs.DirEntry, err error) error {
	if err != nil {
		return err
	}
	fmt.Println("Walking:", path, "Dir?", d.IsDir())
	return nil
})
if err != nil {
	panic(err)
}
```

## What did you expect to happen, and what actually happened instead?

It can read the correct file name and walk to next dir
But it gave garbled code and could not continue to read the next folder
```
D:\build\codes\Go\test>go run main.go
Walking: . Dir? true
Walking: ���� Dir? true
panic: readdir ����: invalid argument

goroutine 1 [running]:
main.main()
        D:/build/codes/Go/test/main.go:25 +0x6b
exit status 2
```
I think the same thing happens when decompressing or maybe other languages

## How do you think this should be fixed?

Maybe the encoding settings needs to be adjusted
Add `traditionalchinese.Big5.NewDecoder().String(path)`
The name can be displayed normally, but it still cannot continue to the next one.

## Please link to any related issues, pull requests, and/or discussion

There are currently no relevant discussions

## Bonus: What do you use this package for, and do you have any other suggestions or feedback?

I use this for backend program API calls

**Comment by mholt** [comment]
Interesting, thanks for providing a test file. I will look at it soon!

**Comment by mholt** [comment]
Ah, yeah, so the text encoding has to be set. I don't know of a way to auto-detect the encoding.

Since FileSystem() abstracts the format away, you'll need to make an [ArchiveFS](https://pkg.go.dev/github.com/mholt/archives#ArchiveFS) directly, using a `Zip` format with the `TextEncoding` field set to whatever your encoding is.

**Comment by Koyorice** [comment]
Thanks! I will try it
