### ISSUE TITLE
`defer compressor.Close()` causes incomplete compression

### ISSUE THREAD

**Issue by jm33-m0** [mholt/archives#8]
## What version of the package or command are you using?

`v0.0.0-20241216060121-23e0af8fe73d`

## What are you trying to do?

```go
// Compress compresses input data using specified compressor.
func Compress(data []byte, compression archives.Compression) ([]byte, error) {
	var compressedBuf bytes.Buffer

	// Wrap the buffer with a compressor
	compressor, err := compression.OpenWriter(&compressedBuf)
	if err != nil {
		return nil, fmt.Errorf("Compress: Failed to create compressor: %w", err)
	}
	defer compressor.Close()

	// Writes to compressor will be compressed
	_, err = compressor.Write(data)
	if err != nil {
		return nil, fmt.Errorf("Compress: Write to compressor failed: %w", err)
	}

	// compressor.Close() without this line, the compressed data will be incomplete
	compressedBytes := compressedBuf.Bytes()

	return compressedBytes, nil
}
```

## What steps did you take?

Compile and run the above function

## What did you expect to happen, and what actually happened instead?

The input file should compress and then decompress without issue.

However, the compressed data is truncated and cannot be decompressed.

## How do you think this should be fixed?

Using `defer compressor.Close()` will somehow close the writer before complete data is written.

**Comment by mholt** [comment]
There is a bug in your code. The `defer compressor.Close()`, which finalizes the compressed stream (necessary for decompressing it), doesn't run until after `compressedBuf.Bytes()`, so you're returning an incomplete stream.

**Comment by jm33-m0** [comment]
Thanks for pointing out. But what's the recommended way of doing it?

**Comment by mholt** [comment]
I would just uncomment the line that makes it work 😌
