### ISSUE TITLE
Opening `"."` in ArchiveFS, when using Stream fails with `invalid argument`

### ISSUE THREAD

**Issue by Linux123123** [mholt/archives#9]
## What version of the package or command are you using?
github.com/mholt/archives v0.0.0-20241216060121-23e0af8fe73d

## What are you trying to do?
I am trying to open an archiveFS (*I don't think it matters that much which one, but it's .tar.gz*) using the `Stream` I provide and then reading the special case `"."`.

## What steps did you take?

<details>
<summary>Small reproduction</summary>

```go
package main

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
)
import "github.com/mholt/archives"

func main() {
	f, err := os.Open("./test.tar.gz")

	if err != nil {
		fmt.Println(err)
		return
	}

	format, _, err := archives.Identify(context.TODO(), "test.tar.gz", f)

	if err != nil && !errors.Is(err, archives.NoMatch) {
		fmt.Println(err)
		_ = f.Close()
		return
	}

	if _, err := f.Seek(0, io.SeekStart); err != nil {
		fmt.Println(err)
		_ = f.Close()
		return
	}

	info, err := f.Stat()

	if err != nil {
		fmt.Println(err)
		_ = f.Close()
		return
	}

	fs := archives.ArchiveFS{Stream: io.NewSectionReader(f, 0, info.Size()), Format: format.(archives.Extraction), Context: context.TODO()}

	archiveDir, err := fs.Open(".") // Fails here with `invalid argument`

	if err != nil {
		fmt.Println(err)
		return
	}

	stat, err := archiveDir.Stat()
	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Println(stat.IsDir())

	_ = archiveDir.Close()

	_ = f.Close()
}
```

</details>

## What did you expect to happen, and what actually happened instead?
I expected the `Open(".")` to return a directory file handle. What actually happened, is that it read everything internally correctly and then failed to close `archiveFile`, which is `nil`, as I am using a `Stream`.

## How do you think this should be fixed?
Before closing handle https://github.com/mholt/archives/blob/23e0af8fe73df29b749ae01ab2de86845585aa44/fs.go#L401 check if the `archiveFile` exists, as currently it tries to close on `nil`.

## Please link to any related issues, pull requests, and/or discussion
N/A or haven't found

## Bonus: What do you use this package for, and do you have any other suggestions or feedback?
I use it to create/extract archives in docker containers. In this context, walking the archive to find if the extracted archive fits in the limited disk space of the containers. (In a downstream version of https://github.com/pterodactyl/wings)

**Comment by mholt** [comment]
Thanks, that's a good find. Appreciate the pointer. Fixed, I think!
